<%@ Page Language="C#" MasterPageFile="~/Customer/Default.master" AutoEventWireup="true" CodeBehind="About Us.aspx.cs" Inherits="HDRS.Customer.About_Us" %>

<%--<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    </form>
</body>
</html>--%>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h2 class="static-page--title" style="margin: 0px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Terms and Conditions</h2>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The Terms and Conditions (T&amp;C) described below constitute an electronic contract, enforceable as per provisions of the Information Technology Act, 2000 and Rules made thereunder, as amended from time to time. Please note that the T &amp; C will not require any signature for acceptance and enforceability. We encourage our esteemed customers to read these terms fully before purchasing any products from our website or mobile apps.</p>
    <h3 class="static-page--subtitle-big" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Offer and Acceptance</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The Customer agrees to these T&amp;C by accessing this Website. All commercial/contractual terms are offered by and agreed to between Customers and Avenue Ecommerce Limited (AEL) alone.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL may include additional or conflicting terms and conditions of sale in the product listing or product description as made available on the website (<b style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">&#39;Additional Terms of Sale&#39;</b>). If there is any conflict between the T&amp;C and the additional terms of sale, the additional terms of sale shall take precedence to the extent of such conflict and in relation to that sale.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL may at any time modify the Terms and Conditions for use of the Website without any prior notification to the customers. If a customer does not agree with the T&amp;C he/she is advised not to buy or attempt to buy any product listed on the Website. However, if the customer continues to use the service he/she shall be deemed to have agreed to accept and abide by the modified Terms &amp; Conditions of Use of this Website.</p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Limitations:</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Services associated with the Website would be available to only select geographies in India as solely determined by AEL.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Persons who are &quot;incompetent to contract&quot; within the meaning of the Indian Contract Act, 1872 as detailed in the Privacy Policy are not eligible to use the Website. AEL shall not be held directly or indirectly liable for any damages arising from the customer’s or any 3rd party’s misuse or violation of the Terms &amp; Conditions of the Dmart site and mobile apps, and any other related policies associated with the Website.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL does not implicitly or explicitly endorse or advertise the products and associated brands on the Website. References on this Website to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to the Customer and do not in any way constitute or imply to be AEL’s endorsement, sponsorship or recommendation of the third party, information, product or service</p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Intellectual Property Rights (IPR):</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL expressly reserves all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Website and mobile apps. Access to this Website does not confer and shall not be considered as conferring upon anyone any license under any of AEL’s or any third party&#39;s intellectual property rights.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Apart from the brands / Intellectual Property Rights (IPR) owned by AEL, all other trademarks/ brands displayed on the Website are the property of their respective brand owners and displayed on the Website with prior consent by AEL.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL hereby allows the Customer to only access the website for personal use and not to download or modify any portion of it. This website or any portion of this Website may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without the express written consent of AEL.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to the Website on or by this Site or otherwise disclosed, submitted or offered in connection with the use of this Website (collectively, the &quot;Feedback&quot;) shall be and remain the property of AEL. Such disclosure, submission or offer of any Feedback on the Website shall constitute an assignment to AEL of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Feedback by the Users.</p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Representation:</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL does not make any Representation or Warranty as to specifics (such as Product claims, manufacturer’s product liability, etc.) of the Products proposed to be sold or offered to be sold or purchased on the Website</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        All offers of sale of a Product are governed by the description and specifications of the Product, terms of warranties provided by the respective manufacturer/brand owners (as applicable) in addition to these Terms and Conditions. In the event a manufacturer/brand owner (as applicable) is providing any warranty, details of such warranty will be specified on the relevant Product webpage on the Website or made available along with the Product. Such warranties are provided by manufacturer/ brand owner (as applicable) and will be fulfilled by the manufacturer/ brand owner (as applicable).</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Warranty:</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        With respect to the sale of Product by AEL to the Customer, AEL hereby represents and warrants to the Customer that:</p>
    <ul class="inner-faq-list" style="margin: 16px 0px; padding: 0px 0px 0px 1.4em; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">AEL has the right to sell the Products to the Customer through the Website;</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Customer shall have and enjoy quiet possession of the Products on completion of sale;</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Products shall be free from any charge or encumbrance in favor of third party;</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Customer shall be entitled to all the warranties and other collaterals applicable to the Product or as generally made available by the manufacturer or brand owner of the Product;</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">AEL has made every effort to display the Products that appear on the Website as accurately as possible. However, any deviance in appearance in actual product cannot be held against AEL.</li>
    </ul>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The Customer hereby represents and warrants to AEL:</p>
    <ul class="inner-faq-list" style="margin: 16px 0px; padding: 0px 0px 0px 1.4em; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">That the Customer is accessing the Website and transacting at his/her sole risk and is using his/her best informed and prudent judgment before entering into any transaction through this Website.</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Customer will use the Website for lawful purposes only and comply with all applicable laws and regulations while using and transacting on the Website.</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Customer will provide authentic and true information in all instances where such information is requested by AEL. AEL reserves the right to confirm and validate the information and other details provided by the customer at any point of time.</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">If upon confirmation the Customer’s details are found not to be true (wholly or partly), AEL has the right in its sole discretion to reject the registration and debar such customer from accessing the Website without prior intimation whatsoever.</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">The address at which delivery of the product ordered by the Customer is to be made will be correct and proper in all respects. Customer is completely responsible and liable for the correctness of delivery address details in this regard.</li>
        <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">That before placing an order customer will check the product description carefully. By placing an order for a product he/she agrees to be bound by the conditions of sale included in the item&#39;s description.</li>
    </ul>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pricing Information:</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        All the products listed on the Website will be sold at MRP unless otherwise specified. The prices mentioned at the time of ordering will be the prices charged on the date of the delivery. All prices are inclusive of GST unless stated otherwise.</p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL may sometimes offer Buy 1 Get 1 products at half price each or less than half price each.</p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Delivery of the Product:</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        AEL currently offers two modes of delivery for purchases made on www.dmart.in.</p>
    <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Home Delivery:</h3>
    <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Please note that for all home deliveries, AEL will charge a delivery fee. This delivery fee will be added to the billed amount at the time of checkout, while placing the order online.</p>
    <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">In case there is a delay in delivering the order to customers – either due to AEL’s own internal reasons or due to customer’s unavailability – AEL is not obligated to compensate the customers for the inconvenience. Customers are liable to pay the entire amount of the order before or at the time of delivery.</li>
    <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For Cash On Delivery customers who choose to pay by a credit/debit card at the time of delivery, AEL will make its best efforts to receive the order amount through a card swipe machine. However, in the event the machine doesn’t work, customers are required to make the payment by cash. Customers agree to not delay payment or seek further time to make the payment once the order is delivered.</li>
    <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AEL reserves the sole right to compensate the customers for any inconvenience caused. A decision to compensate customers for any inconvenience is at the sole discretion of AEL and could happen only through digital payments. Any compensation paid by AEL will be a separate transaction done through digital payment transfer. Customers cannot deduct any agreed compensation amount from the order amount.</li>
    <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Customer agrees to pay the entire order amount (net of any returned items) in full at or before the time of delivery. Exceptions cannot be made in any circumstances.<p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        </p>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Customer Pick Up at DMart Ready Pick-up Points:</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            Customers can collect their orders from DMart Ready Pick-up Points as per their convenience. There are no additional charges for collecting the orders from DMart Ready Pick-up Points.</p>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Tentative Time for Delivery or Pick-up:</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            The typical time that is required to process order is 24 hours from receiving the order online. Please note all items (including gifts) will be shipped with an invoice mentioning the price. There is no guaranteed dispatch time and any information about the dispatch time is estimate only and should not be relied upon as such. Therefore, time is not the essence of the bi-partite contract between the Customer and AEL for purchase and sale of Product through the Website.</p>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            We encourage customers frequenting DMart Ready Pick-up Points to bring their own carry bags to collect their Products. AEL shall charge a fee for a carry bag, if required by the Customer. If you believe that the products you ordered are not in good condition, or if the packaging is tampered with or damaged, please refuse to take delivery of the package. In case you find an issue with the product after accepting delivery, you may return the said product to any of the DMart Ready Pick-up Points and seek recourse as per the terms of refund policy.</p>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            AEL will make its best efforts to service all customer orders accurately and on time. However, if in certain pressing situations (including force majeure), we are unable to fulfill an order we will not recompense the customer for the delay or the non-delivery of the orders.</p>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            Payment: The Product shall not be delivered to the Customer unless the Customer makes the payment of the purchase of Product. In making available any of the payment methods on the Website, AEL will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly because of:</p>
        <ol style="margin: 16px 0px; padding: 0px 0px 0px 1.4em; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Lack of authorization for any transaction/s, or</li>
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Exceeding the preset limit offered by participating banks, or</li>
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Any payment failure arising out of the transaction, or</li>
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">Decline of transaction for any other reason/s</li>
        </ol>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Cancellation:</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            The Customer understands and agrees that the offer for sale of the Product by AEL is not an absolute or an unconditional offer. Such offer to sale by AEL is subject to repudiation by AEL at any time before the delivery of the Product to the Customer, without any obligation to assign or provide any reason for such repudiation, and without any consent from the Customer, and without any liability or any obligation towards the Customer.</p>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Set-off:</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            In case the Customer has availed any benefit in relation to the Product for which the order has been cancelled by the Customer, he/she agrees and authorizes AEL to recover such benefits from the Customer or set-off the same from any refunds to the Customer.</p>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            Return and Refund of Products: Product related complaints for refund or replacement are subject to Refund and Return Policy. Customer and AEL unconditionally agree that they are governed by the Return Policy.</p>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            The return process of a Product may be subject to additional terms depending on the nature and category of the Product. Any such additional terms may be specified on the Website or be intimated by AEL at the time of purchase of the Product.</p>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Governing Law and Jurisdiction</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            By agreeing to these terms and conditions you agree that in case of any dispute you will be governed by the laws of India without reference to conflict of laws principles and exclusive jurisdiction lies with the court of Mumbai.</p>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Limitation of Liability</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            AEL shall not be liable for any special, incidental, direct or consequential damages in connection to terms of use, even if the concerned user has informed in advance about the possibility of damages.</p>
        <h3 class="static-page--subtitle" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Customer Access:</h3>
        <p style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            AEL may deny customers access to the site at any time and may do so immediately without notice. Such denial of access will be without any liability to AEL.</p>
        <h3 class="static-page--subtitle-big" style="margin: 16px 0px 12px; padding: 0px; box-sizing: border-box; touch-action: manipulation; color: rgb(55, 55, 55); font-family: Muli, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Disclaimers</h3>
        <ul style="margin: 16px 0px 16px 1.5rem; padding: 0px 0px 0px 1.4em; box-sizing: border-box; touch-action: manipulation; color: rgb(0, 0, 0); font-family: Muli, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; list-style: disc;">
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">AEL reserves the right to limit the quantity of any given product that a customer can purchase.</li>
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">AEL, at all times, will make its best efforts to ensure that the information (pricing, images, description, color and other defining attributes of the product) about products is accurate. However, in cases where we might inadvertently publish inaccurate information, we will take corrective actions but reserve the right to cancel the order.</li>
            <li style="margin: 0px; padding: 0px; box-sizing: border-box; touch-action: manipulation;">AEL does not take responsibility for any inconvenience or interruption of a customer’s browsing experience arising out of connectivity issues. AEL also does not guarantee 100% availability of our service. From time to time, owing to maintenance activity, our service will be unavailable – during which time we will be unable to service your orders.</li>
        </ul>
    </li>
</asp:Content>